"use client";

import { useState } from "react";
import { cn } from "@/lib/utils";
import { PlusIcon, MinusIcon, DoubleDotsIcon } from "@/components/icons";

interface FaqItem {
  q: string;
  a: string;
}

interface FaqCategory {
  category: string;
  items: FaqItem[];
}

const FAQ_DATA: FaqCategory[] = [
  {
    category: "ABOUT CHAINGPT AI",
    items: [
      {
        q: "What is ChainGPT?",
        a: "ChainGPT is a cutting-edge AI infrastructure focused on developing AI-enhanced solutions for the Web3, Blockchain, and Cryptocurrency sectors. It aims to make the decentralized digital space more accessible and efficient for users and startups by offering a suite of AI-powered tools and applications.",
      },
      {
        q: "Are ChainGPT AI products already available?",
        a: "Yes, ChainGPT AI products are fully available! Crypto AI Hub (most AI tools): app.chaingpt.org · AI NFT Generator: nft.chaingpt.org · ChainGPT Pad: pad.chaingpt.org · Chatbot on Telegram: t.me/chaingptai_bot.",
      },
      {
        q: "What is the cost to use ChainGPT?",
        a: "ChainGPT offers a Free Plan with limited daily access, a Pay-Per-Prompt (PPP) plan billed in CGPT Credits (1 CGPTc = $0.01), and a Freemium Plan for Diamond Tier stakers who receive 20,000 CGPTc monthly.",
      },
      {
        q: "How does ChainGPT work?",
        a: "ChainGPT is a sophisticated AI platform built for Web3, Blockchain, and Crypto ecosystems. Choose Free, Pay-Per-Prompt, or Freemium plans to access tools such as smart contract generation, AI NFT creation, trading assistants, and more, powered by the native $CGPT token.",
      },
      {
        q: "What services can ChainGPT help with?",
        a: "ChainGPT offers a plethora of AI tools: AI Chatbot (Telegram, Discord, Web), AI-Generated News, Smart-Contract Generator & Auditor, AI NFT Generator, AI Trading Assistant, AI-powered Security Extension, Blockchain Analytics, ChainGPT Pad, and Labs incubation — plus open API & SDK access.",
      },
      {
        q: "Are the LLMs (AI-Models) developed by ChainGPT Open-Sourced?",
        a: "No, the LLMs developed by ChainGPT are not open-sourced. However, other projects, startups, and enterprises can quickly and affordably access all ChainGPT products and LLMs through SDK & API access.",
      },
      {
        q: "What are the legal terms on the NFTs / Smart Contracts generated by ChainGPT?",
        a: "Smart contracts generated by ChainGPT's AI are fully owned by the user. IP legality such as copyrights and trademarks is subject to the laws of the user's jurisdiction.",
      },
    ],
  },
  {
    category: "$CGPT UTILITY TOKEN",
    items: [
      {
        q: "What is $CGPT used for?",
        a: "$CGPT powers the entire ChainGPT ecosystem — granting access to premium AI tools, API & SDK usage, DAO voting power, staking & farming rewards, and access to launchpad IDOs.",
      },
      {
        q: "Where can I buy $CGPT?",
        a: "$CGPT is available on major exchanges including Binance, Bybit, and KuCoin, and on DEXs such as PancakeSwap and Raydium.",
      },
    ],
  },
  {
    category: "STAKING & DAO",
    items: [
      {
        q: "How does staking work?",
        a: "Stake $CGPT to earn staking points (CGPTsp) and rewards. Reaching Diamond Tier (200,000+ CGPTsp) unlocks the Freemium plan with 20,000 monthly credits and full DAO rights.",
      },
      {
        q: "What is the ChainGPT DAO?",
        a: "The ChainGPT DAO lets stakers create and vote on proposals that shape the direction of the ecosystem and its products.",
      },
    ],
  },
];

export function FaqSection() {
  const [activeTab, setActiveTab] = useState(0);
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const items = FAQ_DATA[activeTab].items;

  const handleTab = (index: number) => {
    setActiveTab(index);
    setOpenIndex(0);
  };

  return (
    <section id="faq" className="bg-cgpt-bg">
      <div className="mx-auto max-w-[1320px] px-5 py-24 lg:px-8">
        {/* Heading block */}
        <div className="mb-12 max-w-2xl">
          <span className="cgpt-eyebrow flex items-center gap-2 text-cgpt-muted">
            <DoubleDotsIcon className="text-cgpt-violet-light" />
            FAQ
          </span>
          <h2 className="font-sans mt-4 leading-[1.02] text-cgpt-fg text-[clamp(2.5rem,6vw,64px)]">
            Frequently asked
            <br />
            Questions
          </h2>
          <p className="mt-5 text-cgpt-muted">
            Can&apos;t find an answer to your question? Feel free to{" "}
            <a
              href="mailto:info@chaingpt.org"
              className="cgpt-gradient-text font-medium hover:opacity-80"
            >
              contact us
            </a>
            .
          </p>
        </div>

        {/* Category tabs */}
        <div className="mb-4 flex flex-wrap gap-3">
          {FAQ_DATA.map((cat, index) => {
            const active = index === activeTab;
            return (
              <button
                key={cat.category}
                type="button"
                onClick={() => handleTab(index)}
                className={cn(
                  "font-mono relative rounded-md px-5 py-3 text-[12px] uppercase tracking-wide transition-colors",
                  active
                    ? "cgpt-gradient-border text-cgpt-fg"
                    : "border border-cgpt-line text-cgpt-muted hover:text-cgpt-fg"
                )}
              >
                {/* corner brackets on the active tab */}
                {active && (
                  <>
                    <span className="pointer-events-none absolute -left-[3px] -top-[3px] h-2 w-2 border-l border-t border-cgpt-violet-light" />
                    <span className="pointer-events-none absolute -right-[3px] -top-[3px] h-2 w-2 border-r border-t border-cgpt-violet-light" />
                    <span className="pointer-events-none absolute -bottom-[3px] -left-[3px] h-2 w-2 border-b border-l border-cgpt-violet-light" />
                    <span className="pointer-events-none absolute -bottom-[3px] -right-[3px] h-2 w-2 border-b border-r border-cgpt-violet-light" />
                  </>
                )}
                {cat.category}
              </button>
            );
          })}
        </div>

        {/* Accordion */}
        <div className="border-t border-cgpt-line">
          {items.map((item, index) => {
            const open = openIndex === index;
            return (
              <div key={item.q} className="border-b border-cgpt-line">
                <button
                  type="button"
                  onClick={() => setOpenIndex(open ? null : index)}
                  aria-expanded={open}
                  className="flex w-full items-center justify-between gap-6 py-6 text-left"
                >
                  <span
                    className={cn(
                      "font-sans text-[20px] leading-snug transition-colors",
                      open ? "text-cgpt-fg" : "text-cgpt-fg/90 hover:text-cgpt-fg"
                    )}
                  >
                    {item.q}
                  </span>
                  <span
                    className={cn(
                      "flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-cgpt-line transition-colors",
                      open ? "text-cgpt-violet-light" : "text-cgpt-fg"
                    )}
                  >
                    {open ? <MinusIcon /> : <PlusIcon />}
                  </span>
                </button>

                {/* Animated answer panel */}
                <div
                  className={cn(
                    "grid transition-all duration-300 ease-out",
                    open ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"
                  )}
                >
                  <div className="overflow-hidden">
                    <p className="max-w-3xl pb-6 text-[15px] leading-relaxed text-cgpt-muted">
                      {item.a}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
